Repository bmcfee/resampy, pull requests merged in 2022-06, with the labels that each got.

#88 Fixed #76 - matched input and output rates
  resampy/core.py
  tests/test_core.py
Labels: bug

#89 dropped legacy python support
  .github/workflows/ci.yml
  resampy/core.py
  resampy/filters.py
  setup.py
Labels: functionality, packaging

#95 Docs updates
  README.md
  docs/conf.py
  docs/example.rst
  resampy/filters.py
Labels: documentation

#93 Enable parallelism
  .github/workflows/ci-minimal.yml
  resampy/core.py
  resampy/interpn.py
  setup.cfg
  tests/test_quality.py
Labels: functionality

#100 updated changelog
  docs/changes.rst
Labels: documentation
