Repository bmcfee/resampy, pull requests merged in 2022-09, with the labels that each got.

#113 Fix length calculation error
  resampy/core.py
  tests/test_core.py
Labels: bug

#110 Support for 32bit architectures
  resampy/core.py
Labels: functionality

#114 updates for 0.4.1 release
  docs/changes.rst
  resampy/version.py
Labels: documentation, packaging

#115 force floating point math for shape calculations
  resampy/core.py
  tests/test_core.py
Labels: bug
